# Generated by Django 4.0.3 on 2023-03-21 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=50)),
                ('eventimage', models.ImageField(blank=True, null=True, upload_to='events')),
                ('date', models.DateField()),
                ('text_body', models.TextField(max_length=255)),
                ('location', models.TextField(max_length=100)),
            ],
        ),
    ]
